### ISSUE TITLE
Winui 3

### ISSUE THREAD

**Issue by tinmac** [SKProCH/Material.Icons#31] opened 2024-04-07 09:39 UTC
Wondering if you plan on introducing a Winui 3 set?

Would be very welcome

**Comment by SKProCH** [comment] 2024-04-07 11:18
Hello. Did you mean a package for WinUI or some set of WinUI styled icons?

**Comment by tinmac** [comment] 2024-04-07 19:17
A set of material icons we can use in winui 3

**Comment by SKProCH** [comment] 2024-04-07 20:51
It's should probably covered by this project: https://github.com/CastelloBrancoTecnologia/Material.Icons.UNO/

**Comment by tinmac** [comment] 2024-04-10 16:18
@SKProCH Im using WinAppSDK, Material.Icons.Uno is for Uno -> WinUI 3

WinAppSDK/WinUI 3 is gaining a bit of traction now, I have no clue how to go about this so relying on more of an expert in the font field

**Comment by SKProCH** [comment] 2024-04-10 16:30
Sorry, I can't fully get your point. Uno is just basically WinUI3 as far as I understand it. And also WinUI3 is a part of WinAppSDK. And you want a library for the WinAppSDK, so why is the Uno (WinUI) variant not suitable for you? 

I just don't fully understand all this MS's zoo of UI frameworks.

**Comment by tinmac** [comment] 2024-04-10 16:49
[Here](https://github.com/tinmac/WinUI3_MaterialIcons) is a minimal GitHub project showing the issue

I appreciate it isnt your repo as such but it demonstrates the issue

**Comment by SKProCH** [comment] 2024-04-10 19:08
Seems like I can't build your project:

```
dotnet build
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Users\SKProCH\.nuget\packages\microsoft.windowsappsdk\1.4.230913002\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(590,9): error MSB3073: The command ""C:\Users\SKProCH\.nuget\packages\microsoft.windowsappsdk\1.4.230913002\buildTransitive\..\tools\net5.0\..\net472\XamlCompiler.exe" "obj\ARM64\Debug\net8.0-windows10.0.19041.0\\input.json" "obj\ARM
64\Debug\net8.0-windows10.0.19041.0\\output.json"" exited with code 1. [C:\Users\SKProCH\Downloads\WinUI3_MaterialIcons-master\WinUI3_MaterialIcons\WinUI3_MaterialIcons.csproj]
```

Looks like this issue: https://github.com/microsoft/microsoft-ui-xaml/issues/8871

Probably you need to address this issue on the Material.Icons.Uno repository. In fact, the library for Uno/WinUI is located in a different repository, because I couldn't build the library for Uno/WinUI that was offered to me. Details and logs can be read here #26

I would really like to help, but apparently I won’t be able - all of Microsoft’s attempts at UI frameworks after WPF have such shitty cursed tooling that it’s naturally impossible to use them. Sorry.

**Comment by tinmac** [comment] 2024-04-10 20:59
You would need to be on VS 2022 or VS Code (not sure about rider or other IDE's) & on a windows PC for the project to compile & run. 

No worries tho I understand if its not your usual stack. Appreciate you trying to help 👍

**Comment by SKProCH** [comment] 2024-04-11 20:43
Can't manage VS Code to work properly - same error as just `dotnet build`. Forced to install VS, and seems like finally able to compile the project. Such awful developing experience! Require VS installing to just build project - not surprised why all these UI frameworks failed to get community love.

After commenting the button reference in code behind to fix the 
```
The name 'myButton' does not exist in the current contex
```

After that I've getting this exception:
```
Type universe cannot resolve assembly: Uno.UI, Version=255.255.255.255
```

Is this exception what you experience? 

After a bit of googling seems like fix described here:
https://platform.uno/docs/articles/uno-community-toolkit.html?tabs=tabid-winui#referencing-the-windows-community-toolkit-from-a-cross-targeted-library

Probably the problem is in `<PackageReference Include="Uno.WinUI" Version="5.0.48" />` which should be conditionally imported as stated in link above.

**Comment by tinmac** [comment] 2024-04-12 11:14
Sorry for the late reply

I don't see those errors you are getting, did you install the desktop workloads for VS 2022?

In Mainwindow if you comment out `<icons:MaterialIcon ...`  it should build and run ok.

Here is the error I'm seeing

<img width="430" alt="image" src="https://github.com/SKProCH/Material.Icons/assets/6616946/ece12df6-8ec5-43e0-97c7-365c65ba11fb">

**Comment by SKProCH** [comment] 2024-04-12 11:49
Yep, seems like this is similar error. When I'm removing the element app will start fine.

Here is my errors:

![image](https://github.com/SKProCH/Material.Icons/assets/29896317/035e3a5c-c3a6-4f70-8d70-765793ed4539)
![image](https://github.com/SKProCH/Material.Icons/assets/29896317/bc874cbc-b95d-40ca-baec-f6112f22ae11)

Still think what conditional importing should help.

**Comment by tinmac** [comment] 2024-04-12 13:49
Experimenting with the namespace but get a slightly different error

<img width="431" alt="image" src="https://github.com/SKProCH/Material.Icons/assets/6616946/70d40a28-4115-4e95-b1c6-2447a861a511">

**Comment by SKProCH** [comment] 2024-04-28 20:41
This is because `icons2` refer to main library `Material.Icons` which doesn't contains any controls - just icons data.

Still think that this issues should be resolved in Material.Icons.Uno repository using this Uno guide: https://platform.uno/docs/articles/uno-community-toolkit.html?tabs=tabid-winui#referencing-the-windows-community-toolkit-from-a-cross-targeted-library
There is nothing what I can do on my side.

**Closed** 2024-09-07 22:00 UTC
Labels: question
